### ISSUE TITLE
I want to your functions(find, replace, goto line number) merge to https://github.com/megakraken/ICSharpCode.TextEditor

### ISSUE THREAD

**Issue by xyz37** [StefH/ICSharpCode.TextEditorEx#11]
May I add that features with your source to https://github.com/megakraken/ICSharpCode.TextEditor repository ?

**Comment by StefH** [comment]
Yes, you can do that.

However, how much does your version differ from the original version and how much does it differ from my version ?

Because now there are two `extended` versions in github + nuget.

**Comment by xyz37** [comment]
I want to fork to modify the code myself.

**Comment by StefH** [comment]
OK, just copy what you need.

**Comment by xyz37** [comment]
Thanks a lot
