### ISSUE TITLE
nuget package for .NET 5.0

### ISSUE THREAD

**Issue by ghost** [StefH/ICSharpCode.TextEditorEx#12]
Hi

As you know, nuget packages for .NET 4 or .NET Core can't be used in .NET 5.0.

Would it be possible to build an extra nuget package of ICSharpCode.TextEditorEx for .NET 5.0 and put it online on nuget?

I would love to use it in .NET 5.0!

best regards
Jessica

**Comment by maikebing** [comment]
I try to do it

**Comment by maikebing** [comment]
#13
