### ISSUE TITLE
Nuget Version different to Git

### ISSUE THREAD

**Issue by Movian** [StefH/ICSharpCode.TextEditorEx#16]
Trying to figure out how to implement the Syntax files from this project in the NUGET version of this same project...

But unsure which folder it's looking in for the syntax files.

No matter which folder I copy the file to, it states it can't find the file.

can you clarify where to place the xshd file for usage with the NUGET version?

**Comment by StefH** [comment]
Maybe add to https://github.com/StefH/ICSharpCode.TextEditorEx/blob/master/ICSharpCode.TextEditorEx/Resources/SyntaxModes.xml ?

**Comment by StefH** [comment]
closing
