### ISSUE TITLE
Licensing Issues with GPL - for use in closed source

### ISSUE THREAD

**Issue by LukasGelke** [StefH/ICSharpCode.TextEditorEx#19]
Hello, we would like to use your library in our closed source company software. But if I understand the GPL License correctly this is not allowed.
Also please excuse me, but I'm not a lawyer. Don't take this as necessarily correct, as I've written here.
Please don't act sporadically on just my opinion. And please don't take this as an offence in any way.

If I'm understanding correctly from what I've read, you could allow this with some sort of additional exception:
https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

Or of course change to a completely different license which enables this by default. But I'm even less sure if that would still cover the old rights/permissions and wanted restrictions.

for the purposes of my Issue:
- We would use the Lib via NuGet as-is. (This is what the License means with "linking to a library")
- We would propose any potential changes/fixes via this Repo through the usual GitHub conventions
Thus, we do not intend to
- modify your code and keep it closed
- redistribute said closed modifications

I hope you can understand. Feel free to ask/discuss or explain your thoughts.

**Comment by StefH** [comment]
@LukasGelke 

I understand your question, however it's also difficult for me to understand all the licenses.

Some history:
This project is based on https://www.codeproject.com/Articles/30936/Using-ICSharpCode-TextEditor (which seems to have the `MIT` license...
From that source code I created this project, with the help of some other contributors.
I can not recall anymore why I changed this project to `GNU General Public License v2.0`.

When I look at NuGet, there are also some other projects which use the same base code:
- https://www.nuget.org/packages/ICSharpCode.TextEditor (but this one has : https://opensource.org/licenses/lgpl-2.1.php)
- https://www.nuget.org/packages/ICSharpCode.TextEditor.Extended (https://github.com/cepthomas/ICSharpCode.TextEditor.V4/blob/master/LICENSE) (this one has https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html)

So I decided to change my license also to `lgpl-2.1` which is fair to do I think and this license has less restrictions on using it. (See also https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)
