### ISSUE TITLE
Merge Ex code into original

### ISSUE THREAD

**Issue by StefH** [StefH/ICSharpCode.TextEditorEx#6]

**Comment by maximusdm** [comment]
I wasn't sure if I could post a question here. First time using github.
I downloaded your code and was trying to figure out how to add a method I could call to fold/unfold all xml nodes at once (for the current XML file open). Is that possible?
I know I can do it manually on each node but wanted to do it for all nodes automatically - thank you sir.

**Comment by StefH** [comment]
You can post a question at : https://github.com/StefH/ICSharpCode.TextEditorEx/issues/new
